2 css домашнее задание
PashaFevralsky/homework-Purple pull request #2
Opened 2024-05-21 15:52 UTC by PashaFevralsky

2024-05-21 20:18 UTC, Levitinn requested changes

2024-05-21 20:18 UTC, Levitinn commented on 1-blog/styles/styles.css
> +.center {
правый и левый отступ для ширины контента секции задается контейнером. div.class='container' ему задается  max-width и выравнивается по центру

2024-05-21 20:18 UTC, Levitinn commented on 1-blog/index.html
> +                        <h1 class="info__title">
отступы элементов ОТ других элементов это марджин. паддинг это отступ элемента ВНУТРЬ себя.
![image](https://github.com/PashaFevralsky/homework-Purple/assets/44999446/c22c8dfe-5d6e-4f5c-9da7-33680603ac7f)
тут неверно

2024-05-21 20:18 UTC, Levitinn commented on 1-blog/index.html
> +                <div class="author">
![image](https://github.com/PashaFevralsky/homework-Purple/assets/44999446/eb9837ce-fe84-4b45-ace4-2710336d09be)
текст не должен быть в одну строку. плюс так же отступ на марджин переделать нужно. и везде в других местах, где так делал

2024-05-21 20:18 UTC, Levitinn commented on 2-form/index.html
а тут что то не так в целом. какие то слишком большие элементы формы. они явно должны быть других размеров.
![image](https://github.com/PashaFevralsky/homework-Purple/assets/44999446/5ef55da8-2ce8-47b7-bc5a-dd1e336fa7de)
а так же label используешь не совсем корректно. он как бы и есть, но на странице фактически его нет. обрати внимание на ширину пх у этих тегов

2024-05-23 19:59 UTC, Levitinn requested changes
нет исправлений по комментарию о форме

2024-05-25 09:22 UTC, PashaFevralsky commented
Лейблы убрал, по размерам как поняли всё ок, могу мерджить или еще что то пропустил?

2024-05-28 17:39 UTC, merged